<?php
/**
 * CreateLetterRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Doslano Integration API
 *
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Doslano\Model;

use \ArrayAccess;
use \Doslano\ObjectSerializer;

/**
 * CreateLetterRequest Class Doc Comment
 *
 * @category Class
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateLetterRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateLetterRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sender' => '\Doslano\Model\SenderInput',
        'recipients' => '\Doslano\Model\RecipientInput[]',
        'content' => '\Doslano\Model\LetterContent',
        'letter_class' => '\Doslano\Model\LetterClass',
        'promo_code' => 'string',
        'on_promo_invalid' => 'string',
        'on_insufficient_funds' => 'string',
        'dry_run' => 'bool',
        'callback_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sender' => null,
        'recipients' => null,
        'content' => null,
        'letter_class' => null,
        'promo_code' => null,
        'on_promo_invalid' => null,
        'on_insufficient_funds' => null,
        'dry_run' => null,
        'callback_url' => 'uri'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sender' => false,
        'recipients' => false,
        'content' => false,
        'letter_class' => false,
        'promo_code' => false,
        'on_promo_invalid' => false,
        'on_insufficient_funds' => false,
        'dry_run' => false,
        'callback_url' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sender' => 'sender',
        'recipients' => 'recipients',
        'content' => 'content',
        'letter_class' => 'letter_class',
        'promo_code' => 'promo_code',
        'on_promo_invalid' => 'on_promo_invalid',
        'on_insufficient_funds' => 'on_insufficient_funds',
        'dry_run' => 'dry_run',
        'callback_url' => 'callback_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sender' => 'setSender',
        'recipients' => 'setRecipients',
        'content' => 'setContent',
        'letter_class' => 'setLetterClass',
        'promo_code' => 'setPromoCode',
        'on_promo_invalid' => 'setOnPromoInvalid',
        'on_insufficient_funds' => 'setOnInsufficientFunds',
        'dry_run' => 'setDryRun',
        'callback_url' => 'setCallbackUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sender' => 'getSender',
        'recipients' => 'getRecipients',
        'content' => 'getContent',
        'letter_class' => 'getLetterClass',
        'promo_code' => 'getPromoCode',
        'on_promo_invalid' => 'getOnPromoInvalid',
        'on_insufficient_funds' => 'getOnInsufficientFunds',
        'dry_run' => 'getDryRun',
        'callback_url' => 'getCallbackUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ON_PROMO_INVALID_IGNORE = 'ignore';
    public const ON_PROMO_INVALID_REJECT = 'reject';
    public const ON_INSUFFICIENT_FUNDS_REJECT = 'reject';
    public const ON_INSUFFICIENT_FUNDS_HOLD = 'hold';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOnPromoInvalidAllowableValues()
    {
        return [
            self::ON_PROMO_INVALID_IGNORE,
            self::ON_PROMO_INVALID_REJECT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOnInsufficientFundsAllowableValues()
    {
        return [
            self::ON_INSUFFICIENT_FUNDS_REJECT,
            self::ON_INSUFFICIENT_FUNDS_HOLD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('sender', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('letter_class', $data ?? [], null);
        $this->setIfExists('promo_code', $data ?? [], null);
        $this->setIfExists('on_promo_invalid', $data ?? [], 'ignore');
        $this->setIfExists('on_insufficient_funds', $data ?? [], 'reject');
        $this->setIfExists('dry_run', $data ?? [], false);
        $this->setIfExists('callback_url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['recipients'] === null) {
            $invalidProperties[] = "'recipients' can't be null";
        }
        if ((count($this->container['recipients']) > 20)) {
            $invalidProperties[] = "invalid value for 'recipients', number of items must be less than or equal to 20.";
        }

        if ((count($this->container['recipients']) < 1)) {
            $invalidProperties[] = "invalid value for 'recipients', number of items must be greater than or equal to 1.";
        }

        if ($this->container['content'] === null) {
            $invalidProperties[] = "'content' can't be null";
        }
        $allowedValues = $this->getOnPromoInvalidAllowableValues();
        if (!is_null($this->container['on_promo_invalid']) && !in_array($this->container['on_promo_invalid'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'on_promo_invalid', must be one of '%s'",
                $this->container['on_promo_invalid'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOnInsufficientFundsAllowableValues();
        if (!is_null($this->container['on_insufficient_funds']) && !in_array($this->container['on_insufficient_funds'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'on_insufficient_funds', must be one of '%s'",
                $this->container['on_insufficient_funds'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sender
     *
     * @return \Doslano\Model\SenderInput|null
     */
    public function getSender()
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param \Doslano\Model\SenderInput|null $sender Отправитель. Если не указан — берётся отправитель по умолчанию из профиля аккаунта.
     *
     * @return self
     */
    public function setSender($sender)
    {
        if (is_null($sender)) {
            throw new \InvalidArgumentException('non-nullable sender cannot be null');
        }
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \Doslano\Model\RecipientInput[]
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \Doslano\Model\RecipientInput[] $recipients recipients
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        if (is_null($recipients)) {
            throw new \InvalidArgumentException('non-nullable recipients cannot be null');
        }

        if ((count($recipients) > 20)) {
            throw new \InvalidArgumentException('invalid value for $recipients when calling CreateLetterRequest., number of items must be less than or equal to 20.');
        }
        if ((count($recipients) < 1)) {
            throw new \InvalidArgumentException('invalid length for $recipients when calling CreateLetterRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets content
     *
     * @return \Doslano\Model\LetterContent
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param \Doslano\Model\LetterContent $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets letter_class
     *
     * @return \Doslano\Model\LetterClass|null
     */
    public function getLetterClass()
    {
        return $this->container['letter_class'];
    }

    /**
     * Sets letter_class
     *
     * @param \Doslano\Model\LetterClass|null $letter_class letter_class
     *
     * @return self
     */
    public function setLetterClass($letter_class)
    {
        if (is_null($letter_class)) {
            throw new \InvalidArgumentException('non-nullable letter_class cannot be null');
        }
        $this->container['letter_class'] = $letter_class;

        return $this;
    }

    /**
     * Gets promo_code
     *
     * @return string|null
     */
    public function getPromoCode()
    {
        return $this->container['promo_code'];
    }

    /**
     * Sets promo_code
     *
     * @param string|null $promo_code Промокод (опционально).
     *
     * @return self
     */
    public function setPromoCode($promo_code)
    {
        if (is_null($promo_code)) {
            throw new \InvalidArgumentException('non-nullable promo_code cannot be null');
        }
        $this->container['promo_code'] = $promo_code;

        return $this;
    }

    /**
     * Gets on_promo_invalid
     *
     * @return string|null
     */
    public function getOnPromoInvalid()
    {
        return $this->container['on_promo_invalid'];
    }

    /**
     * Sets on_promo_invalid
     *
     * @param string|null $on_promo_invalid Что делать, если промокод не применился: `ignore` — отправить без скидки и вернуть пометку в `pricing.promo`; `reject` — отклонить (422).
     *
     * @return self
     */
    public function setOnPromoInvalid($on_promo_invalid)
    {
        if (is_null($on_promo_invalid)) {
            throw new \InvalidArgumentException('non-nullable on_promo_invalid cannot be null');
        }
        $allowedValues = $this->getOnPromoInvalidAllowableValues();
        if (!in_array($on_promo_invalid, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'on_promo_invalid', must be one of '%s'",
                    $on_promo_invalid,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['on_promo_invalid'] = $on_promo_invalid;

        return $this;
    }

    /**
     * Gets on_insufficient_funds
     *
     * @return string|null
     */
    public function getOnInsufficientFunds()
    {
        return $this->container['on_insufficient_funds'];
    }

    /**
     * Sets on_insufficient_funds
     *
     * @param string|null $on_insufficient_funds Что делать при нехватке средств: `reject` — отклонить (402), письмо не создаётся; `hold` — создать письмо в статусе `awaiting_payment`, оно оплатится автоматически при пополнении баланса.
     *
     * @return self
     */
    public function setOnInsufficientFunds($on_insufficient_funds)
    {
        if (is_null($on_insufficient_funds)) {
            throw new \InvalidArgumentException('non-nullable on_insufficient_funds cannot be null');
        }
        $allowedValues = $this->getOnInsufficientFundsAllowableValues();
        if (!in_array($on_insufficient_funds, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'on_insufficient_funds', must be one of '%s'",
                    $on_insufficient_funds,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['on_insufficient_funds'] = $on_insufficient_funds;

        return $this;
    }

    /**
     * Gets dry_run
     *
     * @return bool|null
     */
    public function getDryRun()
    {
        return $this->container['dry_run'];
    }

    /**
     * Sets dry_run
     *
     * @param bool|null $dry_run Пробный прогон: запрос проходит ПОЛНУЮ реальную валидацию (ключ, scope, IP, файлы, адреса получателей, промокод) и возвращает расчёт цены — но письмо в итоге не создаётся и средства не списываются. Ответ — `200` со схемой `DryRunResult` (вместо `201`/`Letter`). Ошибки валидации возвращаются теми же кодами, что и при реальной отправке (400/422) — это честный тест интеграции. `Idempotency-Key` при `dry_run` игнорируется; `callback_url` не регистрируется; баланс НЕ проверяется (тестируйте хоть с нулевым балансом — сумма к списанию будет в `pricing.total_minor`).
     *
     * @return self
     */
    public function setDryRun($dry_run)
    {
        if (is_null($dry_run)) {
            throw new \InvalidArgumentException('non-nullable dry_run cannot be null');
        }
        $this->container['dry_run'] = $dry_run;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url HTTPS-URL для колбеков по этому письму. Если не указан — используйте поллинг.
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            throw new \InvalidArgumentException('non-nullable callback_url cannot be null');
        }
        $this->container['callback_url'] = $callback_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


