<?php
/**
 * LetterClass
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Doslano Integration API
 *
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Doslano\Model;
use \Doslano\ObjectSerializer;

/**
 * LetterClass Class Doc Comment
 *
 * @category Class
 * @description Тип отправления. Пока поддерживается только заказное (&#x60;registered&#x60;).
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LetterClass
{
    /**
     * Possible values of this enum
     */
    public const REGISTERED = 'registered';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::REGISTERED
        ];
    }
}


