<?php
/**
 * LetterStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Doslano Integration API
 *
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Doslano\Model;
use \Doslano\ObjectSerializer;

/**
 * LetterStatus Class Doc Comment
 *
 * @category Class
 * @description Жизненный цикл письма. Финальные: &#x60;sent&#x60;, &#x60;partial_failure&#x60;, &#x60;error&#x60;, &#x60;cancelled&#x60;.
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LetterStatus
{
    /**
     * Possible values of this enum
     */
    public const FORMING = 'forming';

    public const AWAITING_PAYMENT = 'awaiting_payment';

    public const PAID = 'paid';

    public const SENDING = 'sending';

    public const SENT = 'sent';

    public const PARTIAL_FAILURE = 'partial_failure';

    public const ERROR = 'error';

    public const CANCELLED = 'cancelled';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FORMING,
            self::AWAITING_PAYMENT,
            self::PAID,
            self::SENDING,
            self::SENT,
            self::PARTIAL_FAILURE,
            self::ERROR,
            self::CANCELLED
        ];
    }
}


