<?php
/**
 * RecipientStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Doslano Integration API
 *
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  **Ограничения отправления.** При бумажной форме получения отправление содержит до 4 (четырёх) листов основного документа и лист описи вложения. Ограничение является техническим и изменению не подлежит. Материалы, не воспроизведённые на бумажном носителе, предоставляются получателю в электронной форме по коду доступа и QR-коду, размещённым на листе описи.  **Лимиты по файлам.** Формат — только PDF; до 25 МиБ на файл; к основному документу можно приложить до 10 вложений.  Пересылку, доставку и вручение отправлений осуществляет АО «Почта России» по договору № 3320001147-ОФ от 14 мая 2026 года; doslano оператором почтовой связи не является.  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Doslano\Model;
use \Doslano\ObjectSerializer;

/**
 * RecipientStatus Class Doc Comment
 *
 * @category Class
 * @description Статус отправления получателю. &#x60;sent&#x60; — присвоен трек-номер Почты; финальные: &#x60;delivered&#x60;, &#x60;failed&#x60;.
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecipientStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const QUEUED = 'queued';

    public const SENDING = 'sending';

    public const SENT = 'sent';

    public const DELIVERED = 'delivered';

    public const FAILED = 'failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::QUEUED,
            self::SENDING,
            self::SENT,
            self::DELIVERED,
            self::FAILED
        ];
    }
}


