<?php
/**
 * BalanceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Doslano Integration API
 *
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Doslano\Test\Api;

use \Doslano\Configuration;
use \Doslano\ApiException;
use \Doslano\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BalanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Doslano
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BalanceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getBalance
     *
     * Баланс аккаунта.
     *
     */
    public function testGetBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
